//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dizi_film_blog.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blog()
        {
            this.yorum = new HashSet<yorum>();
        }
    
        public int blogID { get; set; }
        public string blogBaslik { get; set; }
        public string blogIcerik { get; set; }
        public Nullable<System.DateTime> blogTarih { get; set; }
        public string blogGorsel { get; set; }
        public Nullable<byte> blogTur { get; set; }
        public Nullable<byte> blogKategori { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual tur tur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yorum> yorum { get; set; }
    }
}
