//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dizi_film_blog.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public byte mesajID { get; set; }
        public string adSoyad { get; set; }
        public string mail { get; set; }
        public string telefon { get; set; }
        public string konu { get; set; }
        public string mesaj { get; set; }
    }
}
