//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dizi_film_blog.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sosyalMedya
    {
        public int ID { get; set; }
        public string kullaniciAD { get; set; }
        public string link { get; set; }
    }
}
